title: Default File

fields:
  alt:
    label: Alt Text
    type: text
  caption:
    label: Caption
    type: text
  grid_column_end:
    label: Set the grid-column-end span
    type: select
    default: 1
    options:
      1: span 1
      2: span 2
      3: span 3
  grid_row_end:
    label: Set the grid-column-end span
    type: select
    default: 1
    options:
      1: span 1
      2: span 2
      3: span 3