# Each page blueprint must have a title, the title may be different from the file name
title: Project

# Sorting number scheme that is applied when page status is changed to `listed`
# More about page sorting: https://getkirby.com/docs/reference/panel/blueprints/page#sorting
num: date

# Each page can have an icon that is shown in page listings when no preview image is available.
icon: 📖


# Define the form layout with two columns
# Columns are optional but help structure the form layout
# More about columns: https://getkirby.com/docs/guide/blueprints/layout#defining-columns
columns:
  - width: 2/3
    # This columns only has a single field
    fields:
      cover: 
        type: files
        multiple: false
        uploads: false
     
      description:
        type: writer
      text:
        type: blocks
      notes:
        type: writer
      line:
        type: line
      other_files: 
        label: Other relevant files
        layout: cards
        type: files
        multiple: true
        uploads: false
      todos:
        label: Todos
        type: structure
        fields:
          status:
            label: Finished
            type: toggle
            width: 1/4
            text: 
              - "no"
              - "yes"
          task:
            label: Description
            width: 3/4
            type: text
          
         
        


  - width: 1/3
    # This second column holds a fields section with multiple fields
    # More about fields sections: https://getkirby.com/docs/reference/panel/sections/fields
    sections:
      meta:
        type: fields
        fields:
          # If you need the same field in multiple locations, you can define them once and reuse whereever needed.
          # Here we use a files field defined in `/site/blueprints/field/cover.yml`
          client:
            type: text
          werkgever:
            type: text
          materials:
            type: text
          date:
            type: text
          author:
            type: users
          complete:
            label: Complete
            type: toggle
            default: "no"
            text: 
              - "no"
              - "yes"
          # Fields types can be added using the shortcut `fieldname: true`
          # (however, you can only use a fieldname once per page and this only makes sense for simple fields without configuration)
          tags: true
      files:
        type: files
        sortable: true
        layout: gallery
        alt: true

      